### ISSUE TITLE
I do not see the uninstall button

### ISSUE THREAD

**Issue by ZeroCommits** [debanjandhar12/logseq-chatgpt-plugin#14]
![image](https://user-images.githubusercontent.com/37379471/230551738-d5ac99ce-481b-4a31-9067-e0d900478c0c.png)

**Comment by debanjandhar12** [comment]
Sorry, I am failing to replicate this. 
![image](https://user-images.githubusercontent.com/49021233/230552525-5f1d50ed-2213-41ed-8675-ad98d51f59b6.png)

Also, since the plugin is disabled - it is safe to assume that the plugin code is not being executed. I believe this is a bug from your theme (or logseq).
